//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClassRF {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClassRF() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatApp.App_GlobalResources.ClassRF", typeof(ClassRF).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessCode.
        /// </summary>
        public static string AccessCode {
            get {
                return ResourceManager.GetString("AccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add My University .
        /// </summary>
        public static string AddUniversity_btn {
            get {
                return ResourceManager.GetString("AddUniversity-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your University is NOT  in list ,lets add it... .
        /// </summary>
        public static string AddUniversity_msg {
            get {
                return ResourceManager.GetString("AddUniversity-msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminInfo.
        /// </summary>
        public static string AdminInfo {
            get {
                return ResourceManager.GetString("AdminInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        public static string Cancle {
            get {
                return ResourceManager.GetString("Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your Class Successfully Created!.
        /// </summary>
        public static string ClassSuccessfulyCreated {
            get {
                return ResourceManager.GetString("ClassSuccessfulyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create class.
        /// </summary>
        public static string Create_btn {
            get {
                return ResourceManager.GetString("Create-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Class And Give its AccessCode TO your Student....
        /// </summary>
        public static string createInnstriction_msg {
            get {
                return ResourceManager.GetString("createInnstriction-msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreatTitle {
            get {
                return ResourceManager.GetString("CreatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_btn {
            get {
                return ResourceManager.GetString("Edit-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join !.
        /// </summary>
        public static string Join_btn {
            get {
                return ResourceManager.GetString("Join-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of Members that  have been enterd befor you is.
        /// </summary>
        public static string lastMemberCount {
            get {
                return ResourceManager.GetString("lastMemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Class.
        /// </summary>
        public static string LeaveClass_btn {
            get {
                return ResourceManager.GetString("LeaveClass-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Left This Class.
        /// </summary>
        public static string LeftClass_msgHeader {
            get {
                return ResourceManager.GetString("LeftClass-msgHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Hope that,This class was benefit for you....
        /// </summary>
        public static string LeftClass_msgText {
            get {
                return ResourceManager.GetString("LeftClass-msgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberCount.
        /// </summary>
        public static string MemberCount {
            get {
                return ResourceManager.GetString("MemberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Classes.
        /// </summary>
        public static string MyClasses {
            get {
                return ResourceManager.GetString("MyClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok_btn {
            get {
                return ResourceManager.GetString("Ok-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Class Now.
        /// </summary>
        public static string OpenClass {
            get {
                return ResourceManager.GetString("OpenClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your accesscode.
        /// </summary>
        public static string placeHolder {
            get {
                return ResourceManager.GetString("placeHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileImage.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search_btn {
            get {
                return ResourceManager.GetString("search-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of My Classes.
        /// </summary>
        public static string SeeAllClass {
            get {
                return ResourceManager.GetString("SeeAllClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your University .
        /// </summary>
        public static string SelectUniversity {
            get {
                return ResourceManager.GetString("SelectUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniversityId.
        /// </summary>
        public static string UniversityId {
            get {
                return ResourceManager.GetString("UniversityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome to this class.
        /// </summary>
        public static string Welcome_msg {
            get {
                return ResourceManager.GetString("Welcome-msg", resourceCulture);
            }
        }
    }
}
